### ISSUE TITLE
Package is not working with .NET 6

### ISSUE THREAD

**Issue by HerrNiklasRaab** [khellang/EFCore.Sqlite.NodaTime#7]
First of all thanks for the package, it's awesome :)

.NET 6 was released today, after I upgraded I got the following exception:
``` c#
System.TypeLoadException
Method 'GetServiceProviderHashCode' in type 'ExtensionInfo' from assembly 'EntityFrameworkCore.Sqlite.NodaTime, Version=5.1.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at Microsoft.EntityFrameworkCore.Sqlite.Infrastructure.Internal.SqliteNodaTimeOptionsExtension.get_Info()
   at Microsoft.EntityFrameworkCore.DbContextOptions.GetHashCode()
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
   at Brokkoli.Infrastructure.DatabaseContext..ctor(DbContextOptions options) in /Users/niklasraab/Github/brokkoli/brokkoli_backend/Brokkoli.Infrastructure/DatabaseContext.cs:line 12
   at Brokkoli.Application.Test.ServiceTestBase..ctor() in /Users/niklasraab/Github/brokkoli/brokkoli_backend/Brokkoli.Application.Test/ShipmentServiceTest.cs:line 71
   at Brokkoli.Application.Test.ShipmentServiceTest..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
```

This is due to a breaking change in .NET 6. The NodaTime package for SqlServer already faced the same thing, which is documented here: https://github.com/StevenRasmussen/EFCore.SqlServer.NodaTime/issues/23

Here you can find the discussion about the breaking change: https://github.com/dotnet/efcore/issues/26022

**Comment by khellang** [comment]
Hi @HerrNiklasRaab! 👋🏻 

It's nice to hear that someone's actually using the package (besides myself) 😅 

I haven't been able to use .NET 6 in anger yet, but I've pulled it down and opened #8. Hoping to get it merged/pushed to NuGet later tonight 😄

**Comment by khellang** [comment]
Closed by #8

**Comment by khellang** [comment]
Hey @HerrNiklasRaab! There's a new version, v6.0.0, on NuGet if you want to give it a spin 😄

**Comment by HerrNiklasRaab** [comment]
Can confirm it's working now. Thanks!
